# Remote control settings
allow_remote_control yes
listen_on unix:/tmp/kitty

# Cursor
cursor_shape beam
cursor_beam_thickness 10
# cursor_blink_interval 0.5 ease-in-out
# cursor_trail 1 shell_integration no-cursor

# Font
font_family JetBrainsMono NFM SemiBold
font_size 12.0

# Scrolling
wheel_scroll_multiplier 15.0
touch_scroll_multiplier 10.0

# Don't prompt when closing window
confirm_os_window_close 0

# Window padding
window_padding_width 2

# Keybindings
map ctrl+shift+n new_os_window_with_cwd


# BEGIN_KITTY_THEME
# Solarized Light
include current-theme.conf
# END_KITTY_THEME
