# Remote control settings
allow_remote_control yes
listen_on unix:/tmp/kitty

# Font
font_size 12.0

# Scrolling
wheel_scroll_multiplier 3.0

# Window padding
window_padding_width 2

# Keybindings
map ctrl+shift+n new_os_window_with_cwd


# BEGIN_KITTY_THEME
# Solarized Light
include current-theme.conf
# END_KITTY_THEME
