source ~/vc/dotfiles/kak/commands.kak
source ~/vc/dotfiles/kak/options.kak
source ~/vc/dotfiles/kak/key-mapping.kak
source ~/vc/dotfiles/kak/ui.kak
source ~/vc/dotfiles/kak/editorconfig.kak
source ~/vc/dotfiles/kak/modeline.kak
source ~/vc/dotfiles/kak/auto-pairs.kak
source ~/vc/dotfiles/kak/colorscheme.kak
source ~/vc/dotfiles/kak/search.kak
source ~/vc/dotfiles/kak/lsp.kak
